services:
  back1:
    image: backend-cloud
    build:
      context: ./backends
    container_name: back1
#    ports:
#      - "8081:8080"
    networks:
      - cloud-net

  back2:
    image: backend-cloud
    build:
      context: ./backends
    container_name: back2
#    ports:
#      - "8082:8080"
    networks:
      - cloud-net

  load-balancer:
    image: load-balancer
    build:
      context: ./load-balancer
    container_name: load-balancer
    ports:
      - "8080:8080"
    networks:
      - cloud-net

networks:
  cloud-net:
    driver: bridge